import React from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
    exportToPDF,
    printReport
} from "../../../../../utils/reportExport";

import {
    HiOutlineArrowLeft,
    HiOutlinePrinter,
    HiOutlineArrowDownTray,
    HiOutlineDocumentChartBar,
} from "react-icons/hi2";

export default function ReportDetails() {
    const { id } = useParams();
    const navigate = useNavigate();

    const handlePrint = () => {
        printReport();
    };

    const handleExport = () => {
        const columns = ["Field", "Value"];
        const rows = [
            ["Report ID", id],
            ["Report Type", "Payment Report"],
            ["Generated By", "Administrator"],
            ["Generated Date", new Date().toLocaleDateString()],
            ["Status", "Completed"]
        ];
        exportToPDF(`Report-${id}`, columns, rows);
    };

    const wrapper = {
        display: "flex",
        flexDirection: "column",
        gap: "1.5rem" // space-y-6
    };

    const header = {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        flexWrap: "wrap",
        gap: "1rem"
    };

    const headerLeft = {
        display: "flex",
        alignItems: "center",
        gap: "0.75rem" // gap-3
    };

    const backBtn = {
        padding: "0.5rem", // p-2
        borderRadius: "0.5rem", // rounded-lg
        border: "1px solid #e5e7eb",
        backgroundColor: "#ffffff",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        transition: "all 0.2s ease"
    };

    const title = {
        fontSize: "clamp(1.5rem, 5vw, 1.875rem)", // text-3xl
        fontWeight: "700",
        color: "#0f172a",
        margin: 0
    };

    const subtitle = {
        color: "#64748b",
        fontSize: "0.95rem",
        margin: 0
    };

    const btnGroup = {
        display: "flex",
        gap: "0.75rem", // gap-3
        flexWrap: "wrap"
    };

    const btnBase = {
        display: "flex",
        alignItems: "center",
        gap: "0.5rem", // gap-2
        cursor: "pointer",
        padding: "0.5rem 1rem", // px-4 py-2
        borderRadius: "0.5rem", // rounded-lg
        border: "none",
        fontWeight: "600",
        fontSize: "0.95rem",
        transition: "all 0.2s ease"
    };

    const btnBlue = {
       ...btnBase,
        backgroundColor: "#2563eb",
        color: "#ffffff"
    };

    const btnGreen = {
       ...btnBase,
        backgroundColor: "#16a34a",
        color: "#ffffff"
    };

    const card = {
        backgroundColor: "#ffffff",
        borderRadius: "1.5rem", // rounded-2xl
        boxShadow: "0 4px 18px rgba(15, 23, 42, 0.06)",
        border: "1px solid #e5e7eb",
        padding: "clamp(20px, 4vw, 1.5rem)", // p-6 responsive
        width: "100%",
        boxSizing: "border-box",
        fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
    };

    const cardHeader = {
        display: "flex",
        alignItems: "center",
        gap: "0.75rem", // gap-3
        marginBottom: "1.5rem" // mb-6
    };

    const cardTitle = {
        fontSize: "clamp(1.25rem, 4vw, 1.5rem)", // text-2xl
        fontWeight: "700",
        color: "#0f172a",
        margin: 0
    };

    const grid = {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", // 1 col mobile, 2 col tablet, 4 col xl
        gap: "1.5rem" // gap-6
    };

    const label = {
        color: "#64748b",
        fontSize: "0.9rem",
        margin: 0
    };

    const value = {
        fontWeight: "600",
        marginTop: "0.25rem", // mt-1
        color: "#0f172a",
        fontSize: "1rem"
    };

    const statusBadge = {
        display: "inline-block",
        marginTop: "0.25rem",
        backgroundColor: "#dcfce7", // bg-green-100
        color: "#15803d", // text-green-700
        padding: "0.375rem 0.75rem", // px-3 py-1
        borderRadius: "9999px", // rounded-full
        fontSize: "0.85rem",
        fontWeight: "600"
    };

    const previewCard = {
       ...card,
        padding: "clamp(24px, 5vw, 2.5rem)", // p-10 responsive
        textAlign: "center"
    };

    return (
        <div style={wrapper}>
            {/* Header */}
            <div style={header}>
                <div style={headerLeft}>
                    <button
                        onClick={() => navigate(-1)}
                        onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = "#f8fafc"; }}
                        onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = "#ffffff"; }}
                        style={backBtn}
                    >
                        <HiOutlineArrowLeft size={22} />
                    </button>

                    <div>
                        <h1 style={title}>Report Details</h1>
                        <p style={subtitle}>Report ID: {id}</p>
                    </div>
                </div>

                <div style={btnGroup}>
                    <button
                        onClick={handlePrint}
                        onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = "#1d4ed8"; }}
                        onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = "#2563eb"; }}
                        style={btnBlue}
                    >
                        <HiOutlinePrinter />
                        Print
                    </button>

                    <button
                        onClick={handleExport}
                        onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = "#15803d"; }}
                        onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = "#16a34a"; }}
                        style={btnGreen}
                    >
                        <HiOutlineArrowDownTray />
                        Export
                    </button>
                </div>
            </div>

            {/* Report Summary */}
            <div style={card}>
                <div style={cardHeader}>
                    <HiOutlineDocumentChartBar size={28} style={{ color: "#2563eb" }} />
                    <h2 style={cardTitle}>Report Summary</h2>
                </div>

                <div style={grid}>
                    <div>
                        <p style={label}>Report Type</p>
                        <h3 style={value}>Payment Report</h3>
                    </div>

                    <div>
                        <p style={label}>Generated By</p>
                        <h3 style={value}>Administrator</h3>
                    </div>

                    <div>
                        <p style={label}>Generated Date</p>
                        <h3 style={value}>{new Date().toLocaleDateString()}</h3>
                    </div>

                    <div>
                        <p style={label}>Status</p>
                        <span style={statusBadge}>Completed</span>
                    </div>
                </div>
            </div>

            {/* Report Content */}
            <div style={previewCard}>
                <h2 style={cardTitle}>Detailed Report Preview</h2>
                <p style={{ color: "#64748b", marginTop: "1rem", fontSize: "0.95rem", lineHeight: 1.6 }}>
                    This page will display the complete report,
                    charts, statistics and printable data retrieved
                    from the backend.
                </p>
            </div>
        </div>
    );
}